name: faudit  # the name of the snap
version: 0  # the version of the snap
summary: Fireajail audit snap edition  # 79 char long summary
description: faudit program extracted from Firejail and packaged as a snap  # a longer description for the snap
confinement: strict  # use "strict" to enforce system access only via declared interfaces

apps:
    faudit:
        command: /usr/lib/firejail/faudit

parts:
    faudit:  # Replace with a part name of your liking
        # Get more information about plugins by running
        # snapcraft help plugins
        # and more information about the available plugins
        # by running
        # snapcraft list-plugins
        plugin: nil
        snap:
        - usr/lib/firejail/faudit
